name: CI

on: [push]

jobs:
  fix-merge-commit:
    runs-on: [ubuntu-latest]
    # if: github.ref == 'master'
    steps:
    - uses: actions/checkout@v1
    - run: date +%F > todays-date
    - name: Rewrite merge-commit message
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SED_PATTERN: "[pP]ull [rR]equest"
      run: |
        git config user.email "actions@github"
        git config user.name "Github Actions"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        
        # git --no-pager log -1 --format='%B' | grep "$SED_PATTERN" && git commit --amend -m "$(git --no-pager log -1 --format='%B' | sed '1s/$SED_PATTERN \?//')"
           
        # Only commit and push if we have changes
        # git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})
